// MBT spec — model-driven with adapter + oracle
// Generated by MBT framework

import { registerMBTTests } from '../../mbt/runner';
import { generateTestSuite } from '../../mbt/generators/testGenerator';
import { ActorStates } from '../../mbt/models/stateMachine';

const suite = generateTestSuite(ActorStates.USER, 'Authenticated User MBT');
registerMBTTests(suite, 'user');
